name: C/C++ Build (Ubuntu)

on:
  workflow_dispatch:

jobs:
  generate_conanfile:
    uses: nnayar-sms/generate_conanfile_gha/.github/workflows/generate_conanfile_osv_gha.yml@main
    secrets: inherit
